### ISSUE TITLE
CPL format check

### ISSUE THREAD

**Issue by rusefillc** [andreika-git/hellen-one#209]
At the moment we fail to handle the following CPL file https://github.com/andreika-git/hellen-one/blob/master/modules/vr-discrete/0.2/vr-discrete-CPL.csv

```
Designator,Val,Package,Mid X,Mid Y,Rotation,Side
C752,470n,C_0402_1005Metric,-13.750000,4.850000,180.000000,bottom
C753,100n,C_0402_1005Metric,-13.725000,2.925000,0.000000,bottom
C755,1u,C_0402_1005Metric,-11.725000,8.050000,0.000000,bottom
```

with
```
3 parts processed...
4 parts processed...
  ** Inserting Module:vr-discrete/0.2 into M8...
  ** adding vr-discrete_2/0.2 on Top, coords: 0.2905511811023622", 2.977952755905512" (7.38 mm, 75.64 mm)
* appending the CPL with offset (7.38,75.64)...
Traceback (most recent call last):
  File "bin/process_board.py", line 321, in <module>
    append_cpl(module_path + "/" + module_name + "-CPL.csv", board_cpl, x, y, rot, isBottom, module_suffix)
  File "bin/process_board.py", line 126, in append_cpl
    cx = float(cxmm.replace("mm", ""))
ValueError: could not convert string to float: '470n'
ABORTING!
Error: Process completed with exit code 3.
```

question: should we fail with a message "Val column not supported" or "Please have exactly columns X, Y, Z" or shall we simply handle this CPL?

**Comment by rusefillc** [comment]
@Nadezhda-n please match https://github.com/andreika-git/hellen-one/blob/master/modules/vr-discrete/0.1/vr-discrete-CPL.csv

**Comment by rusefillc** [comment]
Looks great!

``Error! Wrong format of CPL file modules/vr-discrete/0.2/vr-discrete-CPL.csv``
