### ISSUE TITLE
explicit success or failure last line message

### ISSUE THREAD

**Issue by rusefillc** [andreika-git/hellen-one#83]
```
Traceback (most recent call last):
  File "bin/process_board.py", line 289, in <module>
    append_bom(module_path + "/" + module_name + "-BOM.csv", board_bom, module_suffix)
  File "bin/process_board.py", line 143, in append_bom
    des = row[1]
IndexError: list index out of range
All done!
```

we need explicit success or failure last line message

**Comment by andreika-git** [comment]
Done.
